salesforceClientConfiguration:
    baseUrl: ""
    timeout: ""
salesforceAuthenticationConfiguration:
    clientId: ""
    clientSecret: ""
grpcHostConfiguration:
    host: "api.pubsub.salesforce.com"
    numberOfEventsToSubscribeInEachFetchRequest: "1"
    plaintextChannel: "false"
    port: "7443"
    replayId: "2"
subscriberConfiguration:
    replayPreset: "LATEST"
    topic: "TOPIC_NAME"