salesforceClientConfiguration:
    baseUrl: ""
    timeout: ""
salesforceAuthenticationConfiguration:
    clientId: ""
    clientSecret: ""
subscriberConfiguration:
    topics:
        -   name: Purchase
            path: /event/Purchase__e
            interval: 5000
        -   name: Order
            path: /event/Order__e
            interval: 5000

pubSubConfiguration:
    host: "api.pubsub.salesforce.com"
    interval: "5000"
    numberOfEventsToSubscribeInEachFetchRequest: "1"
    plaintextChannel: "false"
    port: "7443"
    replayId: "2"
    replayPreset: "LATEST"